### ISSUE TITLE
Incompatibility in modpacks - Oredict ?

### ISSUE THREAD

**Issue by Kalzeroth** [mango-buff/BotanyPotsOrePlanting#1]
Doesn't work for everything in ATM8.

Ingots and blocks from mods are mostly under the AllTheOres mod it seems.

What i can see so far, is that all block are recognized as "soil" but the ingots are not recognized as seeds.

The recipe in JEI shows AllTheOres block for soil, but for exemple the Mekanism mod for the ingot/seed above, but such an ingot doesn't exist in the modpack => it's under the AllTheOres mod like i said before.

This oredict withcraft seems to work for the block but not the ingots 🤷 -> I can put the blocks in the bottom, but not the ingots above

Good luck :D

```
Game Infos:
Minecraft 1.19.2
All the Mods 8-1.0.22
Forge - 43.2.14
BotanyPotsOrePlanting-Forge-3.8.0+1.19.2.jar
```

**Comment by Kalzeroth** [comment]
Totally unrelated and not a bug, so i put it here... If i can make a suggestion, could you move the your recipes from JEI out of the "Crops" thing, and into a new tab for "OreCrops" or something like this ? There is currently 3200 tabs and there is no way i scroll through those to find the recipes :D (Although it does make sense that it's almost always block+ingot)
There's so many tabs because each seed/sapling/crop is shown like 7 times due to the amount of soils available .. :D

**Comment by mango-buff** [comment]
> Totally unrelated and not a bug, so i put it here... If i can make a suggestion, could you move the your recipes from JEI out of the "Crops" thing, and into a new tab for "OreCrops" or something like this ? There is currently 3200 tabs and there is no way i scroll through those to find the recipes :D (Although it does make sense that it's almost always block+ingot) There's so many tabs because each seed/sapling/crop is shown like 7 times due to the amount of soils available .. :D

Sorry, I can't do it.

**Comment by mango-buff** [comment]
> Doesn't work for everything in ATM8.
> 
> Ingots and blocks from mods are mostly under the AllTheOres mod it seems.
> 
> What i can see so far, is that all block are recognized as "soil" but the ingots are not recognized as seeds.
> 
> The recipe in JEI shows AllTheOres block for soil, but for exemple the Mekanism mod for the ingot/seed above, but such an ingot doesn't exist in the modpack => it's under the AllTheOres mod like i said before.
> 
> This oredict withcraft seems to work for the block but not the ingots 🤷 -> I can put the blocks in the bottom, but not the ingots above
> 
> Good luck :D
> 
> ```
> Game Infos:
> Minecraft 1.19.2
> All the Mods 8-1.0.22
> Forge - 43.2.14
> BotanyPotsOrePlanting-Forge-3.8.0+1.19.2.jar
> ```

Oh, let me handle this issue and take a look.
