### ISSUE TITLE
Aluminum bug

### ISSUE THREAD

**Issue by TheDarkShine4** [mango-buff/BotanyPotsOrePlanting#11]
Heya! I do love your mod, but I see just a little problem with it. At least for the 1.19.2 version. While it does take the aluminum block as a soil item, it doesn't take the ingot as a seed item. 
Is there a way to fix this?

**Comment by mango-buff** [comment]
Hello, please provide a screenshot of the issue and the Mod version where the issue is located.

**Comment by Nodachi216** [comment]
@mango-buff 
This is due to a typo in the aluminum_block json in soils. Category is listed as "aluminum_" instead of "aluminum". Dropping the underscore fixes it.
