### ISSUE TITLE
[Error/Question] Parsing error loading recipe - unknown item / Disable All The Ores ?

### ISSUE THREAD

**Issue by wantedkeks** [mango-buff/BotanyPotsOrePlanting#20]
Hej there,
just creating a new modpack, I really enjoying the idea what this mod does!

While joining/creating a world, there is always the same error:

```
Parsing error loading recipe botany_pots_ore_planting:crops/alltheores/copper_ore
com.google.gson.JsonSyntaxException: Unknown item 'alltheores:copper_ingot'
```

There are plenty errors, everyone seems the fault with "all the ores". 

What have I tried yet?
- Just Minecraft, Forge, Botany Pots, Botany Pots Ore Planting: Errors in log, Minecraft works fine
- same setting with the mod All The Ores: Erros sometimes appear, Minecraft works mostly fine
- Full Modpack without ATO: Errors  in log, Minecraft works fine
- Full Modpack with ATO included: Errors and Minecraft crashing.

My question:
I do not want to use ATO. 
Is there a config where to disable the thing with all the ores?
Or is there an easy way to fix it myself, e.g. an instruction/tutorial I have overseen?

What versions do i use?
Minecraft Vanilla 1.20.1
Forge 1.20.1 - 47.2.16
Botany Pots 1.20.1 - 13.0.18
BPOP Botany Pots Ore Planting - 7.4.0+1.20.1

Thank you very much for your time!
If you need more information, please tell me.

**Comment by mango-buff** [comment]
Hmm. At present, there is no way to ban the ore of a certain Mod. If your Minecraft can run normally, please ignore these errors.

**Comment by wantedkeks** [comment]
Alright, thanks for the response. Minecraft works normally, it is just mad that client and server logs keep spamming errors during start and joining a world. Ignoring should be fine, then.

**Comment by mango-buff** [comment]
@wantedkeks Try the latest version now, I've made some adjustments, and it should not report any errors anymore.

**Comment by wantedkeks** [comment]
Thanks for the reply! Unfortunately, I may have time to try by the end of September.
