### ISSUE TITLE
Unable to figure out ars nouveau ore growing

### ISSUE THREAD

**Issue by Stormdemon29** [mango-buff/BotanyPotsOrePlanting#22]
The description doesn't hint at what ars nouveau ores can be grown and also is glowstone an ore that can be grown

**Comment by mango-buff** [comment]
Ars Nouveau in version 1.16.5 allows planting Arcane Ore, but I’m sorry, I don't know if Arcane Ore was removed from Ars Nouveau in version 1.18. 
Regarding Glowstone, I have added it in the latest version.
