### ISSUE TITLE
Powah! Support not working

### ISSUE THREAD

**Issue by Knito58** [mango-buff/BotanyPotsOrePlanting#3]
The description page proudly announces Powah support. But the pot hates everything from the powah mod and JEI knows nothing about it. The support for uranium is for another mod. Powah uses uraninite which is something else. Uraninite comes in raw, refined and block form. There are 6 different ore blocks. I do suggest for simplicity to use the refined uraninite block as dirt and raw uraninite as the plant giving raw uraninite.

**Comment by mango-buff** [comment]
> The description page proudly announces Powah support. But the pot hates everything from the powah mod and JEI knows nothing about it. The support for uranium is for another mod. Powah uses uraninite which is something else. Uraninite comes in raw, refined and block form. There are 6 different ore blocks. I do suggest for simplicity to use the refined uraninite block as dirt and raw uraninite as the plant giving raw uraninite.

There is no problem with actual testing, using Block Of Uraninite as the soil and Raw Uraninite as the seed. MC version 1.16.5

**Comment by Knito58** [comment]
Sorry for me JEI not shows up with the recipe and the pot not wants any of those. Making nether quartz works (should be a proof that I actually have installed the mod). Do I miss a pre-requisite?

**Comment by mango-buff** [comment]
> Sorry for me JEI not shows up with the recipe and the pot not wants any of those. Making nether quartz works (should be a proof that I actually have installed the mod). Do I miss a pre-requisite?

What is the version of your MC?

**Comment by Knito58** [comment]
MC 1.20.1
Forge 47.1.44
Botany Pots 1.20.1-13.0.4
BPOP 7.3.0+1.20.1

but I also have installed

Botany Trees (by the author of Botany Pots, DarkhaxDev) 1.20.1-9.0.3

**Comment by Knito58** [comment]
I just disabled the Botany Trees mod to check but it still not allows for the Powah! components to be filled in. So I will not blame Botany Trees for this issue.

**Comment by mango-buff** [comment]
I seem to know the reason. Are you referring to [Powah (Architected)](https://www.curseforge.com/minecraft/mc-mods/powah-rearchitected) ? Currently, only 1.16.5 of [Powah](https://www.curseforge.com/minecraft/mc-mods/powah) is supported.

**Comment by mango-buff** [comment]
I will support it in the near future.

**Comment by Knito58** [comment]
Correct! It is indeed Powah! (Rearchitected) by thetechnici4n.

**Comment by penturt** [comment]
Powah! (Rearchitected) support would be great as the old Powah By
 owmii is not maintained any longer.

**Comment by mango-buff** [comment]
Support has been added in Forge-2.13.0, Forge-3.10.0, and Forge-7.4.0 versions.

**Comment by penturt** [comment]
Awesome, I'll check it out tomorrow. Thanks for the quick turnaround, I'll be able to remove 3 other mods with just this one.

Question, is amethyst a supported ore/block?

**Comment by mango-buff** [comment]
> Awesome, I'll check it out tomorrow. Thanks for the quick turnaround, I'll be able to remove 3 other mods with just this one.
> 
> Question, is amethyst a supported ore/block?
No, amethyst is not a mineral.

**Comment by Knito58** [comment]
Thanks for updating to Powah! (Rearchitectured). I do confirm it works perfectly.

**Comment by mango-buff** [comment]
> Thanks for updating to Powah! (Rearchitectured). I do confirm it works perfectly.

You're welcome.
