### ISSUE TITLE
Suggestion for more native modded/vanilla ore support!

### ISSUE THREAD

**Issue by Lyfjaberg0666** [mango-buff/BotanyPotsOrePlanting#30]
First of all a big thank you for this mod it helps a lot for modded skyblock challenges as well as a reliable way early game to get yourself started. Now to the suggestions:

Ad Astra: [https://www.curseforge.com/minecraft/mc-mods/ad-astra](url)
form version 1.18.2 onward
Ores in question -> Desh, Ostrum and Calorite

Blue Skies: [https://www.curseforge.com/minecraft/mc-mods/blue-skies](url)
from version 1.18.2 onward
Ores in question -> Pyrobe, Aquite, Diopside, Charoite, Falsite and Horizonite

Create: New Age (Create addon): [https://www.curseforge.com/minecraft/mc-mods/create-new-age](url)
from version 1.19.2 onward
Ore in question -> Thorium (doesn't have a block variante but could use Corium as a replacement)

Enigmatic Legacy: [https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy](url)
from version 1.16.5 onward
Ore in question -> Etherium

Epic Samurai's: [https://www.curseforge.com/minecraft/mc-mods/epic-samurais](url)
from version 1.18.2 onward
Ores in question -> Aquamarine, Jade and Onyx

Forbidden and Arcanus: [https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus](url)
from version 1.18.2 onward
Ores in question -> Stellarite, Arcane Crystal and Rune

More Tetra Materials (Tetra addon): [https://www.curseforge.com/minecraft/mc-mods/more-tetra-materials](url)
from version 1.19.2 onward
Ores in question -> Mithril, Adamantium, Uru and Blood Emerald

Oh The Biomes You'll Go: [https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go](url)
from version 1.16.5 onward
Ores in question -> Anthracite, Ametrine and Pendorite

The Aether: [https://www.curseforge.com/minecraft/mc-mods/aether](url)
from version 1.19.2 onward
Ores in question -> Ambrosium, Zanite and Gravitite

Ulterlands: Worlds Apart: [https://www.curseforge.com/minecraft/mc-mods/the-ulterlands](url)
from version 1.18.2 onward
Ores in question: Aurum, Ferrite, Bloodstone, Etherite and Astrumm

Vault Hunters - Official Mod: [https://www.curseforge.com/minecraft/mc-mods/vault-hunters-official-mod](url)
version 1.18.2 -> Vault Hunters 3rd Edition has already native Botany Pots support
Ores in question -> Alexandrite, Ashium, Benitoite, Black Opal, Bomignite, Echo, Gorginite, Iskallium, Larimar, Painite, Petezanite, Sparkletine, Tubium, Upaline. Wutodie, Xeenium and Chromatic Iron

Minecraft:
from version 1.18.2 onward
Ores in question -> Glowstone and Amethyst

I know it sounds like a lot but I think it would broaden the accessibility for your mod as well as give modpack developers another option to consider if your mod would make the cut to be added to there project or not.
Speaking of accessibility I would like if you could add a full raster of supported mods, minecraft versions and mod loader to your describtion so we can see what is and what isn't included and for which version it is.
For example:
Minecraft: 1.16.5 x | 1.18.2 x | 1.19.2 x | or Vault Hunters - Official Mod: 1.16.5 - | 1.18.2 - | and so on but that is up for you to decide.

**Comment by mango-buff** [comment]
I have added some Mod ores, please refer to the update 1.19.2 for details.
