### ISSUE TITLE
Mod Checking for Install supported Mods

### ISSUE THREAD

**Issue by penturt** [mango-buff/BotanyPotsOrePlanting#6]
I understand the mod supports ores from multiple Mods, by any chance does check to see which mod are installed and prevent loaded assets for mod you are not using? I ask because i'm using the mod on my forge server, and notice error being spammed because "Botany Pots Ore Planting" can't find ores from other mods such as Botania, Thermal, Immersive, Allthemodium which are not on my server.

is that something you can fix, ot just not cause it report because the mods are not installe?

[latest.log](https://github.com/mango-buff/BotanyPotsOrePlanting/files/12384600/latest.log)

**Comment by mango-buff** [comment]
If it does not affect the server startup, then you can ignore this error. After all, I can't do what you said, sorry.
