### ISSUE TITLE
模组配方出现异常

### ISSUE THREAD

**Issue by Liuhahad** [mango-buff/BotanyPotsOrePlanting#8]
模组版本:BotanyPotsOrePlanting-Fabric-3.5.0+1.19.2.jar
游戏版本:1.19.2-Fabric 0.14.22

我在游玩超平坦创造的时候体验了一下模组，发现没办法种植铁矿，JEI也没有显示配方

这个是我的当时状况的图片，目前仅实验了铁矿
![屏幕捕获_2023_08_26_15_17_46_343](https://github.com/mango-buff/BotanyPotsOrePlanting/assets/143250559/f0205ba9-563b-417a-be7e-4d438cba2fe2)
![屏幕捕获_2023_08_26_15_17_53_373](https://github.com/mango-buff/BotanyPotsOrePlanting/assets/143250559/a291d8d5-4060-4198-b147-494f69a45463)

这个是我模组文件夹的图片，不是整合包
![屏幕捕获_2023_08_26_15_12_07_909](https://github.com/mango-buff/BotanyPotsOrePlanting/assets/143250559/734467d0-76b5-4d35-9f2f-04b04a2e9761)
![屏幕捕获_2023_08_26_15_12_23_334](https://github.com/mango-buff/BotanyPotsOrePlanting/assets/143250559/93561abe-c67b-4dd0-b5f5-adbbd34591d4)
![屏幕捕获_2023_08_26_15_12_36_725](https://github.com/mango-buff/BotanyPotsOrePlanting/assets/143250559/7c3d296a-4afd-4968-8ce7-caa73acfeb00)

**Comment by mango-buff** [comment]
模组简介你是一点都不看啊：“种子是对应的矿物锭，土壤是对应的矿物块（个别特殊矿物种植除外）。”

**Comment by mango-buff** [comment]
模组简介你是一点都不看啊：种子是对应的矿物锭，土壤是对应的矿物块（个别特殊矿物种植除外）。
你需要种铁，需要用铁块做土壤

**Comment by Liuhahad** [comment]
哦，不好意思我眼瞎了
希望能在mc百科那加一例子

**Comment by Liuhahad** [comment]
不过我还有一个疑问为什么显示不出配方呢？

**Comment by mango-buff** [comment]
植物盆栽的问题，你需要查询铁锭或铁块的用途
